name: Proxcontrol
description: A mobile Android and iOS application to manage Proxmox VE clusters built with Flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dots_indicator: ^0.0.4
  flutter_launcher_icons: ^0.7.0
  material_design_icons_flutter: ^3.2.3595
  font_awesome_flutter: ^8.4.0
  shared_preferences: ^0.5.1+2
  charts_flutter: ^0.6.0
  flutter_secure_storage: ^3.2.1+1
  http: ^0.11.3+16
  modal_progress_hud: ^0.1.3
  connectivity: ^0.4.2+2
  gradient_widgets: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/Prox Logo.png
    - assets/onboardingBackgroundImage.jpg
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/Nunito.ttf

flutter_icons:
  image_path: "assets/icon.png"
  ios: true
  android: true